language: cpp

compiler:
  - g++-4.8

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

script:
  - g++-4.8 --version
  - cmake .
  - make
  - ./unittest/testrunner
