language: cpp

# see: http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9

script:
  - g++ --version
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER . && make
  - ./unittest/testrunner
